"""create initial tables

Revision ID: c7647bcba8a5
Revises: 
Create Date: 2026-09-25 18:50:09.384749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7647bcba8a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MEMBER',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_code', sa.String(length=30), nullable=False),
    sa.Column('member_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='member_gender'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('is_withdrawn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('member_code')
    )
    op.create_table('PRODUCT',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('tax_category', sa.Enum('standard', 'reduced', name='tax_category'), nullable=False),
    sa.Column('is_abolished', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('STORE',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_code', sa.String(length=20), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_code')
    )
    op.create_table('TAX_RATE',
    sa.Column('tax_rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tax_rate_id')
    )
    op.create_table('DISCOUNT_RULE',
    sa.Column('discount_rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Enum('rate', 'amount', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('member_only', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['PRODUCT.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['STORE.store_id'], ),
    sa.PrimaryKeyConstraint('discount_rule_id')
    )
    op.create_index('idx_dr_product_id', 'DISCOUNT_RULE', ['product_id'], unique=False)
    op.create_index('idx_dr_store_id', 'DISCOUNT_RULE', ['store_id'], unique=False)
    op.create_table('PRODUCT_STORE',
    sa.Column('product_store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['PRODUCT.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['STORE.store_id'], ),
    sa.PrimaryKeyConstraint('product_store_id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_store_product')
    )
    op.create_index('idx_ps_store_id', 'PRODUCT_STORE', ['store_id'], unique=False)
    op.create_table('STAFF',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('staff_code', sa.String(length=20), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('general', 'admin', name='staff_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['STORE.store_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('staff_code')
    )
    op.create_index('idx_staff_store_id', 'STAFF', ['store_id'], unique=False)
    op.create_table('TRANSACTION',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('total_excl_tax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_incl_tax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transacted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['MEMBER.member_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['STAFF.staff_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['STORE.store_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_tx_store_id', 'TRANSACTION', ['store_id'], unique=False)
    op.create_table('TRANSACTION_ITEM',
    sa.Column('transaction_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_excl_tax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['PRODUCT.product_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['TRANSACTION.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TRANSACTION_ITEM')
    op.drop_index('idx_tx_store_id', table_name='TRANSACTION')
    op.drop_table('TRANSACTION')
    op.drop_index('idx_staff_store_id', table_name='STAFF')
    op.drop_table('STAFF')
    op.drop_index('idx_ps_store_id', table_name='PRODUCT_STORE')
    op.drop_table('PRODUCT_STORE')
    op.drop_index('idx_dr_store_id', table_name='DISCOUNT_RULE')
    op.drop_index('idx_dr_product_id', table_name='DISCOUNT_RULE')
    op.drop_table('DISCOUNT_RULE')
    op.drop_table('TAX_RATE')
    op.drop_table('STORE')
    op.drop_table('PRODUCT')
    op.drop_table('MEMBER')
    # ### end Alembic commands ###
