name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main_app-tech0-gen12-08-be.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (check)
        run: |
          python -m venv ../antenv
          source ../antenv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-tech0-gen12-08-be'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
          package: ./backend
